// src/lib/Badge.svelte
<script lang="ts">
	import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";

	import Fa from "svelte-fa";

	export let faIcon: IconDefinition;
	export let title: string;
	export let type: string;
</script>

<span class="badge bg-{type} mx-1 my-1 text-white">
	<Fa icon={faIcon} />
	{title}
</span>

<style lang="scss">
	.badge {
		font-size: 20px;
	}
</style>

// src/components/Badge.tsx
import React from "react";

interface BadgeProps {
	icon: JSX.Element;
	title: string;
	type: string;
}

/**
 * Bootstrap badge component
 */
export default class Badge extends React.Component<BadgeProps> {
	render() {
		return (
			<span
				className={
					"badge bg-" + this.props.type + " mx-1 my-1 text-white"
				}
			>
				{this.props.icon} {this.props.title}
			</span>
		);
	}
}
