// src/components/Button.svelte
<script lang="ts">
	import type { IconDefinition } from "@fortawesome/free-solid-svg-icons";
	import Fa from "svelte-fa";

	export let faIcon: IconDefinition | undefined = undefined;
	export let link: string;
</script>

<a class="btn {$$props.class} mx-2" href={link} role="button">
	{#if faIcon}
		<Fa icon={faIcon} />
	{/if}
	<slot />
</a>

// src/components/Button.tsx
import React from "react";

interface ButtonProps {
	icon: JSX.Element;
	text: string;
	link: string;
}

/**
 * Bootstrap button component
 */
export default class Button extends React.Component<ButtonProps> {
	render() {
		return (
			<a
				className="btn btn-secondary mx-2"
				href={this.props.link}
				role="button"
			>
				{this.props.icon} {this.props.text}
			</a>
		);
	}
}
